fm_elfinder:
    configuration_provider: my_elfinder_configurator
    instances:
        ckeditor:
            locale: %locale%
            editor: ckeditor # other choices are tinymce or simple
            include_assets: true
            relative_path: true
            connector:
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['all']